name: 'Deploy to AWS S3'
description : 'Deployment a static website via s3'
inputs:
  bucket: 
    description: 'The S3 bucket name'
    required: true
  bucket-region: 
    description: 'The S3 bucket  region name '
    required: false
    default: 'ap-southeast-2'
  dist-folder: 
    description: 'The folder contain deployable files'
    required: true
    
outputs: 
  website-url: 
     description: 'The URL of the deployable website'      
runs: 
  using: 'docker'
  image: 'Dockerfile'
