name: 04-Using Actions 

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Printing Folders 
              run: ls -R
            - name: Present Working Directory 
              run: pwd   
            - name: List files from working directory
              run: ls -l
              working-directory: MyWorkflows      
            


        

  